### ISSUE TITLE
Change Storage path so it can be accessed at everywhere

### ISSUE THREAD

**Issue by athif23** [Leoat12/toread-cli#7]
So, how about instead of saving or create the 'file.json' in some folder, we create it or save it at some place where it can be accessed everywhere?

For, example:

```
	E:\Users\Project\toread-cli
	$ to-read saveArticle <someurl>
```

This code (in the latest version) will create 'file.json' in the `\toread-cli` folder. But, when we do:

```
	C:\Someplace\Someplacetoo\folder1
	$ to-read saveArticle <someurl>
```

Instead of taking the already existing data that we just created, it will create a new `file.json` file inside `folder1` folder. We or more precisely I don't want that. I want the data to be available in every folder we in.

I have researched how we can do that, by looking at the [taskbook](https://github.com/klauscfhq/taskbook) codebase. And, I pretty much make it working fine, already. But, the problem is, I'm still not sure if it would be good or bad. Please let me hear your opinion? Should I PR it or not?

Thanks.

**Comment by Leoat12** [comment]
That's fantastic! Go ahead and do the PR. 
I think the idea was doing it later when the project was mature enough, but I think this time has come and I kind of forgot about that.

**Comment by athif23** [comment]
**Closed**. See at #9.
